name: spring-initializr Build

on:
  push:
    branches: [ "main", "develop", "feature/**", "fix/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'spring-io/initializr'
      - name: patch sample service pom
        run: |
          sed -i 's|</project>|<build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build></project>|' initializr-sample-service/pom.xml
      - name: update initializr config
        run: |
          curl https://raw.githubusercontent.com/spring-io/start.spring.io/main/start-site/src/main/resources/application.yml -o initializr-sample-service/src/main/resources/application.yml
      - name: Set up JDK 21
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 21
      - name: Build with Maven
        run: mvn spring-boot:build-image --file initializr-sample-service/pom.xml -Dspring-boot.build-image.imageName=helmstart/spring-initializr
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Image
        run: docker push helmstart/spring-initializr:latest
      - name: deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker pull helmstart/spring-initializr:latest && 
            wget -O docker-compose.yml https://raw.githubusercontent.com/helm-start/helm-start/develop/docker-compose.yml &&
            docker compose up -d --force-recreate --no-deps initializr

